apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: remotesecret-release-to-quay-rhtap-ser
  namespace: rhtap-spi-tenant
spec:
  application: remotesecret
  target: rhtap-releng-tenant
