apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: integration-service-release-to-quay-rhtap-ser
  namespace: rhtap-integration-tenant
spec:
  application: integration-service
  target: rhtap-releng-tenant
