apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: send-slack-notification-secret-remote-secret
  namespace: rhtap-releng-tenant
spec:
  secret:
    name: slack-notification-secret
    type: Opaque
    linkedTo:
      - serviceAccount:
          reference:
            name: konflux-servicerelease-sa
  targets:
    - namespace: rhtap-releng-tenant
