apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: infra-deployments-pr-creator-remote-secret
  namespace: rhtap-releng-tenant
spec:
  secret:
    name: infra-deployments-pr-creator
    type: Opaque
    linkedTo:
      - serviceAccount:
          reference:
            name: konflux-servicerelease-sa
  targets:
    - namespace: rhtap-releng-tenant
