apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: quay-token-redhat-acm-remote-secret
  namespace: rhtap-releng-tenant
spec:
  secret:
    linkedTo:
    - serviceAccount:
        reference:
          name: redhat-acm-service-account
    name: quay-token-secret
    type: kubernetes.io/dockerconfigjson
  targets:
  - namespace: rhtap-releng-tenant
